version: "3"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
    container_name: flask_app
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=AKIA5VRCA3XYC4MBUBW3
      - AWS_SECRET_ACCESS_KEY=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

  db:
    image: mysql:5.6
    ports:
      - "32000:3306"
    container_name: database_1
    environment:
      MYSQL_ROOT_PASSWORD: "Yokocat22"
