version: "3"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
    container_name: flask_app
    restart: always

  db:
    image: mysql:5.6
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Yokocat22"